version: '3'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chattercart
    ports:
      - "3306:3306"

  redis:
    image: redis
    ports:
      - "6379:6379"
